name: Build Slither Image

on:
  workflow_dispatch:
    inputs:
      slither-version:
        description: 'Slither version'
        required: true
      solc-version:
        description: 'Solc version'
        required: true
        default: '0.8.30'
      latest:
        description: 'Additional tags to add beyond version-solc'
        required: true
        type: choice
        default: none
        options:
          - none
          - solc
          - all

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set image name
        id: image_name
        run: echo "image_name=ghcr.io/$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')/slither" >> $GITHUB_OUTPUT

      - name: Log in to the GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v6
        with:
          context: ./tools/slither
          push: true
          build-args: |
            SLITHER_VERSION=${{ github.event.inputs.slither-version }}
            SOLC_VERSION=${{ github.event.inputs.solc-version }}
          tags: |
            ${{ steps.image_name.outputs.image_name }}:${{ github.event.inputs.slither-version }}-solc${{ github.event.inputs.solc-version }}
            ${{ github.event.inputs.latest != 'none' && format('{0}:{1}', steps.image_name.outputs.image_name, github.event.inputs.slither-version) || '' }}
            ${{ github.event.inputs.latest == 'all' && format('{0}:latest', steps.image_name.outputs.image_name) || '' }}
